### ISSUE TITLE
Can't launch the NeoForge client/server in the 1.21.8

### ISSUE THREAD

**Issue by SAGESSE-CN** [architectury/architectury-loom#294]
in the fabric version it work normally, but can't work in neoforge, it will say:

```
[01:51:29] [main/FATAL] [ne.ne.fm.ModLoader/CORE]: Error during pre-loading phase: NeoForge dev environment client-extra jar does not have a Minecraft-Dists attribute in its manifest; this may be because you have an out-of-date gradle plugin
```

Architect Plugin: 3.4.161
Architectury Loom: 1.10.434

log: https://pastebin.com/iDF9vhGT

<img width="1439" height="899" alt="Image" src="https://github.com/user-attachments/assets/4a254e75-400c-4d36-bbfd-ac3701514169" />

**Comment by Juuxel** [comment]
This issue was fixed in f62514260a48425140673e143700908b89d05808 (1.10.443).

Since your Loom version looks correct, try running Gradle with `-Dloom.refresh=true` to regenerate the broken game jar. If you tried to run that game version on an older version of Loom, the jar might have broken contents from that.

**Comment by SAGESSE-CN** [comment]
https://maven.shedaniel.me/dev/architectury/loom/dev.architectury.loom.gradle.plugin/

the latest version only exists is 1.10.434

**Comment by SAGESSE-CN** [comment]
i tried 
```
./gradle -Dloom.refresh=true
```
and use `1.10-SNAPSHOT`

the problem still exists.

**Comment by Juuxel** [comment]
It was a typo 😅 I meant build 433. The latest version should work.
